### ISSUE TITLE
iCal format for cross-platform compatibility

### ISSUE THREAD

**Issue by lenarddome** [openresearchcalendar/Open-Research-Calendar#1]
Most calendar clients (e.g. Outlook) need an iCal calendar link. Providing a webcal link would make it easier to integrate into any calendar.

**Comment by b-kennedy0** [comment]
Hi - Thank you for the suggestion. We've added this to the ORC Webpage, 2nd Paragraph of 'Overview' section (https://openresearchcalendar.github.io/Open-Research-Calendar/) . 

Also now added to pinned tweet on Twitter (https://twitter.com/OpenResearchCal/status/1272319159632900097)

#2
